embeddings {
  tensor_name: "sku:00090"
  metadata_path: "00090/sku\\metadata.tsv"
  tensor_path: "00090/sku\\tensors.tsv"
}
embeddings {
  tensor_name: "agency:00090"
  metadata_path: "00090/agency\\metadata.tsv"
  tensor_path: "00090/agency\\tensors.tsv"
}
embeddings {
  tensor_name: "month:00090"
  metadata_path: "00090/month\\metadata.tsv"
  tensor_path: "00090/month\\tensors.tsv"
}
