embeddings {
  tensor_name: "Store:00300"
  metadata_path: "00300/Store\\metadata.tsv"
  tensor_path: "00300/Store\\tensors.tsv"
}
embeddings {
  tensor_name: "week:00300"
  metadata_path: "00300/week\\metadata.tsv"
  tensor_path: "00300/week\\tensors.tsv"
}
