embeddings {
  tensor_name: "Store:00030"
  metadata_path: "00030/Store\\metadata.tsv"
  tensor_path: "00030/Store\\tensors.tsv"
}
embeddings {
  tensor_name: "week:00030"
  metadata_path: "00030/week\\metadata.tsv"
  tensor_path: "00030/week\\tensors.tsv"
}
