embeddings {
  tensor_name: "Store:00090"
  metadata_path: "00090/Store\\metadata.tsv"
  tensor_path: "00090/Store\\tensors.tsv"
}
embeddings {
  tensor_name: "week:00090"
  metadata_path: "00090/week\\metadata.tsv"
  tensor_path: "00090/week\\tensors.tsv"
}
